/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Codigo.CPU;

/**
 *
 */
public class CPUpane extends javax.swing.JPanel {

    /**
     * Creates new form CPUpane
     */
    private CPU cpu;
    
    public CPUpane(CPU cpu) {
        this.cpu = cpu;
        initComponents();
        actualizarInterfaz();
        
         this.setMinimumSize(new java.awt.Dimension(300, 200));
    this.setPreferredSize(new java.awt.Dimension(300, 200));
    this.setMaximumSize(new java.awt.Dimension(300, 200));
    }

    
    public void actualizarInterfaz() {
        IDcpuLabel.setText(String.valueOf(cpu.getsId()));
        
        
        // Actualiza los valores en los labels con los datos del CPU y su proceso
        NombreProcesoLabel.setText(cpu.getProceso() != null ? cpu.getProceso().getNombre() : "Proceso System");
        IDprocesoLabel.setText(cpu.getProceso() != null ? String.valueOf(cpu.getProceso().getId()) : "N/A" );
        PCprocesoLabel.setText(cpu.getProceso() != null ? String.valueOf(cpu.getProceso().getPC()) : "N/A");
        MARprocesoLabel.setText(cpu.getProceso() != null ? String.valueOf(cpu.getProceso().getMAR()) : "N/A");
        StatusprocesoLabel.setText(cpu.getProceso() != null ? String.valueOf(cpu.getProceso().getEstado()) : "N/A");
        TipoprocesoLabel.setText(cpu.getProceso() != null ? cpu.getProceso().getTipo() : "N/A");
    }

    public void actualizarConProceso() {
        // Método público para actualizar la interfaz si el proceso cambia
        actualizarInterfaz();
    }
    
    public void liberarCPU(){
        NombreProcesoLabel.setText("Sin proceso");
        IDprocesoLabel.setText("N/A");
        PCprocesoLabel.setText("N/A");
        MARprocesoLabel.setText("N/A");
        StatusprocesoLabel.setText("N/A");
        TipoprocesoLabel.setText("N/A");
    
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IDcpuLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        NombreProcesoLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IDprocesoLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PCprocesoLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MARprocesoLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        StatusprocesoLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TipoprocesoLabel = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        IDcpuLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        IDcpuLabel.setText("1");
        add(IDcpuLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 20, 30));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("CPU");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 75, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel3.setText("Proceso en Ejecución:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, 60));

        NombreProcesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        NombreProcesoLabel.setText("Nombre del Proceso");
        add(NombreProcesoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 140, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel5.setText("ID:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, 60));

        IDprocesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        IDprocesoLabel.setText("ID proceso");
        add(IDprocesoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 140, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel7.setText("PC:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, -1, 60));

        PCprocesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        PCprocesoLabel.setText("PC proceso");
        add(PCprocesoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 140, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel9.setText("MAR:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 70, -1, 60));

        MARprocesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        MARprocesoLabel.setText("MAR proceso");
        add(MARprocesoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, 140, 60));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel11.setText("Status:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, -1, 60));

        StatusprocesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        StatusprocesoLabel.setText("Status proceso");
        add(StatusprocesoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 140, 60));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel13.setText("Tipo:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, -1, 60));

        TipoprocesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        TipoprocesoLabel.setText("Tipo proceso");
        add(TipoprocesoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 140, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDcpuLabel;
    private javax.swing.JLabel IDprocesoLabel;
    private javax.swing.JLabel MARprocesoLabel;
    private javax.swing.JLabel NombreProcesoLabel;
    private javax.swing.JLabel PCprocesoLabel;
    private javax.swing.JLabel StatusprocesoLabel;
    private javax.swing.JLabel TipoprocesoLabel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
