/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;

import javax.swing.*;
import java.awt.*;
import proyecto1.gabriele.yoarly.MainClass;

/**
 *
 */
public class GraficoTorta extends javax.swing.JPanel {
    private DefaultPieDataset dataset;
    /**
     * Creates new form GraficoTorta
     */
    public GraficoTorta() {
        initComponents();
         dataset = new DefaultPieDataset();
        dataset.setValue("CPU Bound", MainClass.ProcesosCPUtotales);
        dataset.setValue("I/O Bound", MainClass.ProcesosIOtotales);

        // Crear el gráfico
        JFreeChart chart = ChartFactory.createPieChart(
                "Distribución de Procesos", // Título
                dataset,                   // Dataset
                true,                      // Incluir leyenda
                true,                      // Incluir tooltips
                false                      // URLs no necesarias
        );

        // Crear un panel para el gráfico
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(500, 400));

        // Configurar el panel actual
        setLayout(new BorderLayout());
        add(chartPanel, BorderLayout.CENTER);
    }

    public void actualizarDatos() {
        // Actualizar los valores del dataset
        dataset.setValue("CPU Bound", MainClass.ProcesosCPUtotales);
        dataset.setValue("I/O Bound", MainClass.ProcesosIOtotales);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 483, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables


}
