/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import Codigo.Proceso;

/**
 *
 */
public class ListaPane extends javax.swing.JPanel {
    private Proceso proceso;
    /**
     * Creates new form ListaPane
     */
    public ListaPane(Proceso proceso) {
        this.proceso = proceso;
        initComponents();

        this.setMinimumSize(new java.awt.Dimension(100, 150));
        this.setPreferredSize(new java.awt.Dimension(100, 150));
        this.setMaximumSize(new java.awt.Dimension(100, 150));

        actualizarInterfaz(); // Llama al método para actualizar las etiquetas
    }
    
    public void actualizarInterfaz() {
    // Actualiza los valores de las etiquetas con los datos del proceso
    NombreProcesoLabel.setText(proceso.getNombre() != null ? proceso.getNombre() : "Sin Nombre");
    IDprocesoLabel.setText(proceso.getId() != 0 ? String.valueOf(proceso.getId()) : "N/A");
    PCprocesoLabel.setText(String.valueOf(proceso.getPC()));
    MARprocesoLabel.setText(String.valueOf(proceso.getMAR()));
    StatusprocesoLabel.setText(proceso.getEstado() != null ? proceso.getEstado() : "N/A");
    TipoprocesoLabel.setText(proceso.getTipo() != null ? proceso.getTipo() : "N/A");
}
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombreProcesoLabel = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        IDprocesoLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        PCprocesoLabel = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        MARprocesoLabel = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        StatusprocesoLabel = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TipoprocesoLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        NombreProcesoLabel.setText("Nombre del Proceso");
        add(NombreProcesoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 20));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel5.setText("ID:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 60));

        IDprocesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        IDprocesoLabel.setText("ID proceso");
        add(IDprocesoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 140, 60));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel7.setText("PC:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, 60));

        PCprocesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        PCprocesoLabel.setText("PC proceso");
        add(PCprocesoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 30, 140, 60));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel9.setText("MAR:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 60));

        MARprocesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        MARprocesoLabel.setText("MAR proceso");
        add(MARprocesoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 140, 60));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel11.setText("Status:");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, 60));

        StatusprocesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        StatusprocesoLabel.setText("Status proceso");
        add(StatusprocesoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 140, 60));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel13.setText("Tipo:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, 60));

        TipoprocesoLabel.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        TipoprocesoLabel.setText("Tipo proceso");
        add(TipoprocesoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 140, 60));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel IDprocesoLabel;
    private javax.swing.JLabel MARprocesoLabel;
    private javax.swing.JLabel NombreProcesoLabel;
    private javax.swing.JLabel PCprocesoLabel;
    private javax.swing.JLabel StatusprocesoLabel;
    private javax.swing.JLabel TipoprocesoLabel;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
